#...................
#
# my_first_workflow
#
#...................

name: hello-world

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Say hello
        run: make say-hello


  my_testing:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello message
        run: echo "Hello World!"
