#...................
#
# my_first_workflow
#
#...................

name: hello-world
env:
  APL_NAME: "myFlask"
  PACKAGE_NAME: "flask_deploy_version-${{ github.sha}}"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Say hello
        run: make say-hello


  my_testing:
    runs-on: ubuntu-latest
    needs: [build]
    
    steps:
      - name: Print Hello message
        run: echo "Hello World!"
        
      - name: Package
        run: |
          echo "hello message1"
          echo "Name: ${{ env.PACKAGE_NAME}}"
          
      - name: Git clone my repo
        uses: actions/checkout@v1
